"""Regenerate local web fonts: python -m pip install fonttools brotli; python web/scripts/sync-fonts.py.

TTF sources and their OFL licenses live in public/fonts. UI characters are
derived from source; characters outside this subset load the full font on demand.
"""
from pathlib import Path
from hashlib import sha256
from fontTools.ttLib import TTFont
from fontTools import subset

web = Path(__file__).resolve().parents[1]
fonts = web / 'public/fonts'


def save(font, stem):
    font.flavor = 'woff2'
    from io import BytesIO
    output = BytesIO()
    font.save(output)
    data = output.getvalue()
    name = f'{stem}-{sha256(data).hexdigest()[:12]}.woff2'
    (fonts / name).write_bytes(data)
    print(name, len(data))
    return name


def face(family, name, weights, ranges=''):
    return f'''@font-face {{
  font-family: "{family}";
  font-style: normal;
  font-weight: {weights};
  font-display: swap;
  src: url("/fonts/{name}") format("woff2");
{f'  unicode-range: {ranges};' if ranges else ''}
}}
'''


lexend = save(TTFont(fonts / 'lexend-variable.ttf'), 'lexend')
noto = save(TTFont(fonts / 'noto-sans-sc-variable.ttf'), 'noto-sans-sc')
characters = set()
for path in (web / 'src').rglob('*'):
    if path.suffix in ('.tsx', '.ts'):
        characters.update(ord(c) for c in path.read_text(encoding='utf-8') if ord(c) > 127)
font = TTFont(fonts / 'noto-sans-sc-variable.ttf')
characters &= set(font.getBestCmap())
subsetter = subset.Subsetter()
subsetter.populate(unicodes=characters)
subsetter.subset(font)
ui = save(font, 'noto-sans-sc-ui')
# The later, restricted face wins for UI characters. The complete face is only
# downloaded for characters absent from the UI, not on every first visit.
css = '/* Generated by scripts/sync-fonts.py */\n'
css += face('Lexend', lexend, '100 900')
css += face('JetBrains Mono', 'jetbrains-mono-latin.woff2', '500 600')
css += face('Noto Sans SC', noto, '100 900')
css += face('Noto Sans SC', ui, '100 900', ', '.join(f'U+{c:X}' for c in sorted(characters)))
(web / 'src/fonts.css').write_text(css, encoding='utf-8')
