"""MCDR 实例生命周期管理。

本面板把每个 MCDR 实例当作「外部被管理对象」:
  - 创建:生成实例目录结构 + config.yml/permission.yml/eula + 下载 vanilla 服务端 jar
  - 启停:以子进程方式运行 ``python -m mcdreforged``,通过 stdin 发送 ``stop``
  - 状态:由文件系统标记 + 进程存活情况派生

进程句柄保存在内存(单进程部署)。重启面板会丢失句柄,届时实例显示为 stopped。
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import shlex
import shutil
from collections import deque
from collections.abc import Callable
from pathlib import Path

import yaml

from . import jar_cache
from .config import SERVERS_ROOT
from .models import Server
from .versions import get_server_download

# 状态常量
STATUS_INSTALLING = "installing"
STATUS_ERROR = "error"
STATUS_NEW_SETUP = "new_setup"
STATUS_STARTING = "starting"
STATUS_RUNNING = "running"
STATUS_STOPPED = "stopped"

# 服务端加载完成标志:vanilla 输出 'Done (12.345s)! For help, ...'
_DONE_RE = re.compile(r"Done \([\d.,]+s\)!")

_INSTALLING_MARKER = ".installing"
_FAILED_MARKER = ".install_failed"

# 控制台:每个实例在内存里保留的最近日志行数,以及订阅队列的上限。
_CONSOLE_BUFFER_LINES = 500
_SUBSCRIBER_QUEUE_MAXSIZE = 1000


def sanitize_dir_name(name: str) -> str:
    """把服务器名净化成安全的目录名。"""
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", name.strip())
    cleaned = cleaned.strip("._") or "server"
    return cleaned[:80]


def _eula_text() -> str:
    return (
        "# Generated by mc-panel. By setting eula=true you agree to the "
        "Minecraft EULA (https://aka.ms/MinecraftEULA).\n"
        "eula=true\n"
    )


def _server_properties_text(port: int) -> str:
    return "\n".join(
        [
            "#Minecraft server properties (generated by mc-panel)",
            f"server-port={port}",
            "online-mode=true",
            "max-players=20",
            "view-distance=10",
            "motd=A Minecraft Server",
            "enable-rcon=false",
            "",
        ]
    )


# 服务器类型 -> MCDR 输出解析 handler(均为 MCDR 内置)
HANDLERS = {
    "vanilla": "vanilla_handler",
    "fabric": "vanilla_handler",
    "forge": "forge_handler",
    "velocity": "velocity_handler",
}


def _resolve_launch(inst: "Path", server_type: str) -> tuple[str, str]:
    """根据已安装文件决定启动目标:('-jar', jar) 或 ('@', argsfile)。"""
    sd = inst / "server"
    if server_type == "forge":
        # 现代 Forge(1.17+):@libraries/.../win_args.txt
        args = sorted(sd.glob("libraries/net/minecraftforge/forge/*/win_args.txt"))
        if args:
            return ("@", str(args[0].relative_to(sd)).replace("\\", "/"))
        # 旧版 Forge:forge-*.jar(排除 installer)
        jars = [p for p in sd.glob("forge-*.jar") if "installer" not in p.name]
        if jars:
            return ("-jar", jars[0].name)
    return ("-jar", "server.jar")


def build_start_command(
    java_command: str,
    min_memory: str,
    max_memory: str,
    extra_jvm_args: str = "",
    server_type: str = "vanilla",
    launch: tuple[str, str] = ("-jar", "server.jar"),
) -> list[str]:
    """组装服务端启动命令:java + 内存 + UTF-8 + 额外参数 + 启动目标。"""
    try:
        extra = shlex.split(extra_jvm_args) if extra_jvm_args else []
    except ValueError:
        extra = extra_jvm_args.split()
    cmd = [
        java_command,
        f"-Xms{min_memory}",
        f"-Xmx{max_memory}",
        # 强制服务端以 UTF-8 输出,避免 Windows 下控制台用系统码页(GBK)导致乱码
        "-Dfile.encoding=UTF-8",
        *extra,
    ]
    mode, value = launch
    if mode == "@":
        cmd.append(f"@{value}")
    else:
        cmd += ["-jar", value]
    if server_type != "velocity":  # 代理端无 GUI 概念
        cmd.append("nogui")
    return cmd


def _mcdr_config(
    java_command: str,
    min_memory: str,
    max_memory: str,
    extra_jvm_args: str = "",
    server_type: str = "vanilla",
    launch: tuple[str, str] = ("-jar", "server.jar"),
) -> dict:
    """构造 MCDR config.yml 内容(handler 与启动命令按服务器类型)。"""
    return {
        "language": "zh_cn",
        "working_directory": "server",
        "start_command": build_start_command(
            java_command, min_memory, max_memory, extra_jvm_args, server_type, launch
        ),
        "handler": HANDLERS.get(server_type, "vanilla_handler"),
        # 发送给服务端用 UTF-8;读取服务端输出先按 UTF-8,失败回退 GBK
        # (Windows 下 Java 启动器/旧服务端常用系统码页),避免解码报错。
        "encoding": "utf8",
        "decoding": ["utf8", "gbk"],
        "plugin_directories": ["plugins"],
        "check_update": False,
        "advanced_console": False,
        "telemetry": False,
    }


def _velocity_toml(port: int) -> str:
    """完整的 Velocity 默认配置(带 bind 端口)。

    Velocity 要求配置合法(至少有 [servers] 与可用的 try 回退)才会启动,
    因此写入官方默认模板而非精简版。首次启动会生成 forwarding.secret。
    """
    return f"""# Config version. Do not change this
config-version = "2.7"
bind = "0.0.0.0:{port}"
motd = "<#09add3>A Velocity Server"
show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "NONE"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"
sample-players-in-ping = false
enable-player-address-logging = true

[servers]
lobby = "127.0.0.1:30066"
try = [
    "lobby"
]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true
accepts-transfers = false

[query]
enabled = false
port = {port}
map = "Velocity"
show-plugins = false
"""


def _permission_text() -> str:
    return "\n".join(
        ["default_level: user", "owner:", "admin:", "helper:", "user:", "guest:", ""]
    )


class MCDRManager:
    def __init__(self) -> None:
        # server_id -> asyncio subprocess
        self._procs: dict[int, asyncio.subprocess.Process] = {}
        # server_id -> 最近日志行的环形缓冲(供控制台连接时回放历史)
        self._buffers: dict[int, deque[str]] = {}
        # server_id -> 订阅该实例输出的队列集合(每个 WebSocket 连接一个)
        self._subscribers: dict[int, set[asyncio.Queue[str]]] = {}
        # server_id -> 读取 stdout 的后台任务
        self._reader_tasks: dict[int, asyncio.Task] = {}
        # server_id -> (已下载字节, 总字节);安装/下载进度
        self._install_progress: dict[int, tuple[int, int]] = {}
        # server_id -> 安装(下载)任务,用于中止
        self._install_tasks: dict[int, asyncio.Task] = {}
        # 已完成启动(出现 Done 行)的实例 id 集合;用于区分「启动中 / 运行中」
        self._ready: set[int] = set()
        # 运行中被改了配置/模组、需要重启才生效的实例 id 集合
        self._needs_restart: set[int] = set()
        # 开机自启队列中(等待前序优先级就绪)的实例 id 集合
        self._queued: set[int] = set()
        # server_id -> 开服(Done)后要自动执行的指令
        self._startup_cmds: dict[int, list[str]] = {}
        # 逐行钩子(如玩家绑定验证):每条输出行都会调用,异常被吞掉
        self.line_hook: "Callable[[int, str], None] | None" = None

    # ---------- 路径 ----------
    def instance_dir(self, server: Server) -> Path:
        return SERVERS_ROOT / server.dir_name

    def clear_stale_installing(self) -> None:
        """启动时调用:残留的 .installing 标记都已失效(下载随进程退出无法续传),
        统一转成失败标记,让实例显示为「异常」并可重新安装,而不是永远「安装中」。"""
        if not SERVERS_ROOT.exists():
            return
        for inst in SERVERS_ROOT.iterdir():
            marker = inst / _INSTALLING_MARKER
            if marker.exists():
                marker.unlink(missing_ok=True)
                (inst / _FAILED_MARKER).write_text(
                    "安装被中断(服务重启),请点「重新安装」重试", encoding="utf-8"
                )

    def is_running(self, server_id: int) -> bool:
        p = self._procs.get(server_id)
        return p is not None and p.returncode is None

    def mark_needs_restart(self, server_id: int) -> None:
        """运行中的实例被改了配置/模组时调用,标记为需要重启。"""
        if self.is_running(server_id):
            self._needs_restart.add(server_id)

    def needs_restart(self, server_id: int) -> bool:
        return server_id in self._needs_restart and self.is_running(server_id)

    def _core_installed(self, server: Server) -> bool:
        """核心是否已就绪。Forge 现代版无 server.jar,改判 args 文件 / forge jar。"""
        sd = self.instance_dir(server) / "server"
        if server.server_type == "forge":
            if any(sd.glob("libraries/net/minecraftforge/forge/*/win_args.txt")):
                return True
            return any(p for p in sd.glob("forge-*.jar") if "installer" not in p.name)
        return (sd / "server.jar").exists()

    # ---------- 状态 ----------
    def get_status(self, server: Server) -> str:
        inst = self.instance_dir(server)
        if (inst / _INSTALLING_MARKER).exists():
            return STATUS_INSTALLING
        if (inst / _FAILED_MARKER).exists():
            return STATUS_ERROR
        if not self._core_installed(server):
            return STATUS_NEW_SETUP
        proc = self._procs.get(server.id)
        if proc is not None and proc.returncode is None:
            return STATUS_RUNNING if server.id in self._ready else STATUS_STARTING
        if server.id in self._queued:
            return "queued"
        return STATUS_STOPPED

    # ---------- 安装进度 / 任务 ----------
    def install_progress(self, server_id: int) -> tuple[int, int] | None:
        return self._install_progress.get(server_id)

    def set_install_task(self, server_id: int, task: asyncio.Task) -> None:
        self._install_tasks[server_id] = task

    def clear_install_task(self, server_id: int) -> None:
        self._install_tasks.pop(server_id, None)
        self._install_progress.pop(server_id, None)

    async def cancel_install(self, server: Server) -> None:
        """中止进行中的安装:取消下载任务并把实例标记为失败(可重试)。"""
        task = self._install_tasks.get(server.id)
        if task is not None and not task.done():
            task.cancel()
        inst = self.instance_dir(server)
        (inst / _INSTALLING_MARKER).unlink(missing_ok=True)
        (inst / _FAILED_MARKER).write_text("已取消安装,可点「重试」重新下载", encoding="utf-8")
        self._install_progress.pop(server.id, None)
        self._install_tasks.pop(server.id, None)

    async def _install_core(self, server: Server, java_command: str) -> None:
        """按服务器类型下载/安装核心到 server/ 目录。耗时,放后台。"""
        from . import versions as ver

        server_dir = self.instance_dir(server) / "server"
        dest = server_dir / "server.jar"
        prog = lambda d, t: self._install_progress.__setitem__(server.id, (d, t))  # noqa: E731
        st = server.server_type

        if st == "vanilla":
            info = await get_server_download(server.mc_version)
            size = info.get("size", 0) or 0
            self._install_progress[server.id] = (0, size)
            await jar_cache.cached_download(
                info["url"], dest, algo="sha1", hexhash=info.get("sha1", ""), size=size,
                progress=lambda d, t: prog(d, size or t),
            )
        elif st == "fabric":
            info = await ver.get_fabric_download(server.mc_version, server.loader_version)
            self._install_progress[server.id] = (0, 0)
            await ver.download_file(info["url"], dest, progress=prog)
        elif st == "velocity":
            info = await ver.get_velocity_download(server.loader_version)
            size = info.get("size", 0) or 0
            self._install_progress[server.id] = (0, size)
            await jar_cache.cached_download(
                info["url"], dest, algo="sha256", hexhash=info.get("sha256", ""), size=size,
                progress=lambda d, t: prog(d, size or t),
            )
        elif st == "forge":
            meta = await ver.get_forge_installer(server.mc_version, server.loader_version)
            installer = server_dir / meta["name"]
            self._install_progress[server.id] = (0, 0)
            await ver.download_file(meta["url"], installer, progress=prog)
            # 运行官方安装器生成服务端文件(需联网拉依赖)
            self._install_progress[server.id] = (0, 0)
            proc = await asyncio.create_subprocess_exec(
                java_command or "java", "-jar", meta["name"], "--installServer",
                cwd=str(server_dir),
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
            )
            out, _ = await proc.communicate()
            if proc.returncode != 0:
                tail = (out or b"").decode("utf-8", "replace")[-500:]
                raise RuntimeError(f"Forge 安装器失败(code {proc.returncode}): {tail}")
            installer.unlink(missing_ok=True)
        else:
            raise RuntimeError(f"不支持的服务器类型: {st}")

    # ---------- 创建 ----------
    async def create_instance(self, server: Server, java_command: str) -> None:
        """生成实例目录并安装核心。耗时较长,应在后台任务中调用。"""
        inst = self.instance_dir(server)
        server_dir = inst / "server"
        marker = inst / _INSTALLING_MARKER
        failed = inst / _FAILED_MARKER
        is_proxy = server.server_type == "velocity"

        try:
            for sub in (server_dir, inst / "plugins", inst / "config", inst / "logs"):
                sub.mkdir(parents=True, exist_ok=True)
            if failed.exists():
                failed.unlink()
            marker.write_text("installing", encoding="utf-8")
            self._install_progress[server.id] = (0, 0)

            (inst / "config.yml").write_text(
                yaml.safe_dump(
                    _mcdr_config(
                        java_command, server.min_memory, server.max_memory,
                        server.extra_jvm_args, server.server_type,
                    ),
                    allow_unicode=True,
                    sort_keys=False,
                ),
                encoding="utf-8",
            )
            (inst / "permission.yml").write_text(_permission_text(), encoding="utf-8")
            if is_proxy:
                (server_dir / "velocity.toml").write_text(
                    _velocity_toml(server.port), encoding="utf-8"
                )
            else:
                (server_dir / "eula.txt").write_text(_eula_text(), encoding="utf-8")
                (server_dir / "server.properties").write_text(
                    _server_properties_text(server.port), encoding="utf-8"
                )

            await self._install_core(server, java_command)

            # 安装后按实际文件重建启动命令(Forge 需定位 args 文件 / jar)
            self.apply_start_command(server, java=java_command)

            marker.unlink(missing_ok=True)
            self._install_progress.pop(server.id, None)
        except Exception as exc:  # noqa: BLE001 - 记录失败原因供前端显示
            marker.unlink(missing_ok=True)
            failed.write_text(str(exc), encoding="utf-8")
            self._install_progress.pop(server.id, None)
            raise

    # ---------- 控制台:缓冲与订阅 ----------
    def _append_line(self, server_id: int, line: str) -> None:
        buf = self._buffers.setdefault(server_id, deque(maxlen=_CONSOLE_BUFFER_LINES))
        buf.append(line)
        # 检测服务端加载完成,把状态从「启动中」翻成「运行中」
        if server_id not in self._ready and "Done (" in line and _DONE_RE.search(line):
            self._ready.add(server_id)
            cmds = self._startup_cmds.get(server_id) or []
            if cmds:
                try:
                    asyncio.get_running_loop().create_task(self._send_startup(server_id, cmds))
                except RuntimeError:
                    pass

    async def _send_startup(self, server_id: int, cmds: list[str]) -> None:
        for c in cmds:
            await asyncio.sleep(1)
            try:
                await self.send_raw(server_id, c)
            except Exception:  # noqa: BLE001
                break
        for queue in list(self._subscribers.get(server_id, set())):
            try:
                queue.put_nowait(line)
            except asyncio.QueueFull:
                pass  # 慢消费者:丢弃该行而非阻塞读取
        if self.line_hook is not None:
            try:
                self.line_hook(server_id, line)
            except Exception:  # noqa: BLE001 - 钩子异常不能影响日志读取
                pass

    def recent_lines(self, server_id: int) -> list[str]:
        return list(self._buffers.get(server_id, ()))

    def subscribe(self, server_id: int) -> asyncio.Queue[str]:
        queue: asyncio.Queue[str] = asyncio.Queue(maxsize=_SUBSCRIBER_QUEUE_MAXSIZE)
        self._subscribers.setdefault(server_id, set()).add(queue)
        return queue

    def unsubscribe(self, server_id: int, queue: asyncio.Queue[str]) -> None:
        subs = self._subscribers.get(server_id)
        if subs:
            subs.discard(queue)

    async def _read_output(self, server_id: int, proc: asyncio.subprocess.Process) -> None:
        """持续读取子进程输出,逐行写入缓冲并广播给订阅者。"""
        assert proc.stdout is not None
        while True:
            raw = await proc.stdout.readline()
            if not raw:
                break
            self._append_line(server_id, raw.decode("utf-8", errors="replace").rstrip("\r\n"))
        rc = proc.returncode
        self._ready.discard(server_id)
        self._append_line(server_id, f"[mc-panel] 进程已退出 (return code: {rc})")

    def _reconcile_config(self, inst: Path) -> None:
        """启动前同步实例 config.yml 的编码字段,让早于编码修复创建的实例也受益。
        只改 encoding/decoding,不动用户可能自定义的 start_command。"""
        config_path = inst / "config.yml"
        if not config_path.exists():
            return
        try:
            data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001 - 配置损坏时不阻塞启动
            return
        if data.get("encoding") == "utf8" and data.get("decoding") == ["utf8", "gbk"]:
            return
        data["encoding"] = "utf8"
        data["decoding"] = ["utf8", "gbk"]
        config_path.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8"
        )

    # ---------- 编辑:把改动落到实例文件 ----------
    def apply_start_command(self, server: Server, java: str | None = None) -> None:
        """按 server 的内存/额外 JVM 参数重建 config.yml 的 start_command。
        java 为 None 时沿用现有 start_command[0](默认 'java')。"""
        config_path = self.instance_dir(server) / "config.yml"
        if not config_path.exists():
            return
        try:
            data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001
            return
        override = (getattr(server, "start_command_override", "") or "").strip()
        if override:
            data["start_command"] = override
        else:
            if java is None:
                cmd = data.get("start_command")
                java = cmd[0] if isinstance(cmd, list) and cmd else "java"
            launch = _resolve_launch(self.instance_dir(server), server.server_type)
            data["start_command"] = build_start_command(
                java, server.min_memory, server.max_memory, server.extra_jvm_args,
                server.server_type, launch,
            )
        lang = (getattr(server, "mcdr_language", "") or "").strip()
        if lang:
            data["language"] = lang
        config_path.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8"
        )

    # ---------- server.properties ----------
    def _properties_path(self, server: Server) -> Path:
        return self.instance_dir(server) / "server" / "server.properties"

    def read_properties(self, server: Server) -> dict[str, str]:
        path = self._properties_path(server)
        result: dict[str, str] = {}
        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                stripped = line.lstrip()
                if not stripped or stripped.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                result[key.strip()] = value
        return result

    def write_properties(self, server: Server, updates: dict[str, str]) -> None:
        """更新 server.properties 中给定键,保留其余行/注释/顺序。"""
        path = self._properties_path(server)
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
        seen: set[str] = set()
        out: list[str] = []
        for line in lines:
            stripped = line.lstrip()
            if stripped and not stripped.startswith("#") and "=" in line:
                key = line.split("=", 1)[0].strip()
                if key in updates:
                    out.append(f"{key}={updates[key]}")
                    seen.add(key)
                    continue
            out.append(line)
        for key, value in updates.items():
            if key not in seen:
                out.append(f"{key}={value}")
        path.write_text("\n".join(out) + "\n", encoding="utf-8")

    def apply_port(self, server: Server) -> None:
        if server.server_type == "velocity":
            self._apply_velocity_bind(server)
        else:
            self.write_properties(server, {"server-port": str(server.port)})

    def _apply_velocity_bind(self, server: Server) -> None:
        """改写 velocity.toml 的 bind 端口;文件不存在则写完整默认模板。"""
        path = self.instance_dir(server) / "server" / "velocity.toml"
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_velocity_toml(server.port), encoding="utf-8")
            return
        text = path.read_text(encoding="utf-8")
        new_text, n = re.subn(
            r'(?m)^bind\s*=\s*".*"', f'bind = "0.0.0.0:{server.port}"', text
        )
        if n == 0:
            new_text = f'bind = "0.0.0.0:{server.port}"\n' + text
        path.write_text(new_text, encoding="utf-8")

    def _ensure_velocity_config(self, server: Server) -> None:
        """velocity.toml 缺失或不合法(无 [servers]/try)时重写完整默认模板,保留端口。"""
        path = self.instance_dir(server) / "server" / "velocity.toml"
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_velocity_toml(server.port), encoding="utf-8")
            return
        text = path.read_text(encoding="utf-8")
        if "[servers]" in text and "try" in text:
            return
        m = re.search(r'bind\s*=\s*"[^"]*:(\d+)"', text)
        port = int(m.group(1)) if m else server.port
        path.write_text(_velocity_toml(port), encoding="utf-8")

    def read_velocity_config(self, server: Server) -> dict:
        """读取 velocity.toml 的常用项供前端编辑。"""
        import tomllib

        path = self.instance_dir(server) / "server" / "velocity.toml"
        data: dict = {}
        if path.exists():
            try:
                data = tomllib.loads(path.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                data = {}
        return {
            "motd": str(data.get("motd", "")),
            "show_max_players": int(data.get("show-max-players", 500) or 500),
            "online_mode": bool(data.get("online-mode", True)),
            "forwarding_mode": str(data.get("player-info-forwarding-mode", "NONE")),
        }

    def write_velocity_config(self, server: Server, updates: dict) -> None:
        path = self.instance_dir(server) / "server" / "velocity.toml"
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_velocity_toml(server.port), encoding="utf-8")
        text = path.read_text(encoding="utf-8")

        def set_str(t: str, key: str, val: str) -> str:
            val = val.replace("\\", "\\\\").replace('"', '\\"')
            nt, n = re.subn(rf'(?m)^{re.escape(key)}\s*=\s*".*"$', f'{key} = "{val}"', t)
            return nt if n else t.rstrip("\n") + f'\n{key} = "{val}"\n'

        def set_raw(t: str, key: str, val: str) -> str:
            nt, n = re.subn(rf'(?m)^{re.escape(key)}\s*=\s*.*$', f"{key} = {val}", t)
            return nt if n else t.rstrip("\n") + f"\n{key} = {val}\n"

        if "motd" in updates:
            text = set_str(text, "motd", str(updates["motd"]))
        if "show_max_players" in updates:
            text = set_raw(text, "show-max-players", str(int(updates["show_max_players"])))
        if "online_mode" in updates:
            text = set_raw(text, "online-mode", "true" if updates["online_mode"] else "false")
        if "forwarding_mode" in updates:
            text = set_str(text, "player-info-forwarding-mode", str(updates["forwarding_mode"]))
        path.write_text(text, encoding="utf-8")

    async def redownload_jar(self, server: Server, java_command: str = "java") -> None:
        """重装核心(换版本/重试):重跑类型对应安装,保留世界/配置。"""
        inst = self.instance_dir(server)
        server_dir = inst / "server"
        server_dir.mkdir(parents=True, exist_ok=True)
        marker = inst / _INSTALLING_MARKER
        failed = inst / _FAILED_MARKER
        try:
            failed.unlink(missing_ok=True)
            marker.write_text("installing", encoding="utf-8")
            self._install_progress[server.id] = (0, 0)
            await self._install_core(server, java_command)
            self.apply_start_command(server, java=java_command)
            marker.unlink(missing_ok=True)
            self._install_progress.pop(server.id, None)
        except Exception as exc:  # noqa: BLE001
            marker.unlink(missing_ok=True)
            failed.write_text(str(exc), encoding="utf-8")
            self._install_progress.pop(server.id, None)
            raise

    # ---------- 启停 ----------
    async def start(
        self, server: Server, python_executable: str, java_path: str | None = None
    ) -> None:
        inst = self.instance_dir(server)
        if not self._core_installed(server):
            raise RuntimeError("核心尚未安装完成")
        if server.server_type == "velocity":
            self._ensure_velocity_config(server)  # 自愈无效的 velocity.toml
        self._reconcile_config(inst)
        # 用所选 java + 当前内存/额外参数重建启动命令
        self.apply_start_command(server, java=java_path)
        existing = self._procs.get(server.id)
        if existing is not None and existing.returncode is None:
            return  # 已在运行
        self._needs_restart.discard(server.id)
        self._queued.discard(server.id)
        try:
            self._startup_cmds[server.id] = json.loads(server.startup_commands or "[]")
        except Exception:  # noqa: BLE001
            self._startup_cmds[server.id] = []

        # 强制 MCDR(Python)以 UTF-8 读写其 stdio,否则 Windows 下会用系统码页(GBK)
        # 写日志,我们按 UTF-8 解码就会乱码。这样无论宿主机区域设置如何都统一为 UTF-8。
        env = {**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"}
        proc = await asyncio.create_subprocess_exec(
            python_executable,
            "-m",
            "mcdreforged",
            cwd=str(inst),
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            env=env,
        )
        self._procs[server.id] = proc
        # 新一轮运行:清空旧缓冲、重置启动完成标志,并启动输出读取任务
        self._ready.discard(server.id)
        self._buffers[server.id] = deque(maxlen=_CONSOLE_BUFFER_LINES)
        self._append_line(server.id, "[mc-panel] 实例已启动")
        self._reader_tasks[server.id] = asyncio.create_task(self._read_output(server.id, proc))

    async def send_command(self, server: Server, command: str) -> None:
        await self.send_raw(server.id, command)

    async def send_raw(self, server_id: int, command: str) -> None:
        proc = self._procs.get(server_id)
        if proc is None or proc.returncode is not None or proc.stdin is None:
            raise RuntimeError("实例未在运行")
        try:
            proc.stdin.write((command.rstrip("\n") + "\n").encode("utf-8"))
            await proc.stdin.drain()
        except (BrokenPipeError, ConnectionResetError) as exc:
            raise RuntimeError("无法写入实例标准输入") from exc

    async def stop(self, server: Server) -> None:
        self._needs_restart.discard(server.id)
        proc = self._procs.get(server.id)
        if proc is None or proc.returncode is not None:
            self._procs.pop(server.id, None)
            return
        if proc.stdin is not None:
            try:
                proc.stdin.write(b"stop\n")
                await proc.stdin.drain()
            except (BrokenPipeError, ConnectionResetError):
                proc.terminate()

    async def force_stop(self, server: Server) -> None:
        """强杀:连同子进程(MCDR 派生的 Java 服务端)一起 kill。"""
        self._needs_restart.discard(server.id)
        proc = self._procs.get(server.id)
        if proc is None:
            return
        try:
            import psutil

            parent = psutil.Process(proc.pid)
            for child in parent.children(recursive=True):
                try:
                    child.kill()
                except Exception:  # noqa: BLE001
                    pass
            parent.kill()
        except Exception:  # noqa: BLE001
            try:
                proc.kill()
            except Exception:  # noqa: BLE001
                pass
        self._procs.pop(server.id, None)

    async def delete_instance(self, server: Server) -> None:
        await self.stop(server)
        self._procs.pop(server.id, None)
        inst = self.instance_dir(server)
        if inst.exists():
            shutil.rmtree(inst, ignore_errors=True)


# 单例
manager = MCDRManager()
