"""MCDR 实例生命周期管理。

本面板把每个 MCDR 实例当作「外部被管理对象」:
  - 创建:生成实例目录结构 + config.yml/permission.yml/eula + 下载 vanilla 服务端 jar
  - 启停:以子进程方式运行 ``python -m mcdreforged``,通过 stdin 发送 ``stop``
  - 状态:由文件系统标记 + 进程存活情况派生

进程句柄保存在内存(单进程部署)。重启面板会丢失句柄,届时实例显示为 stopped。
"""
from __future__ import annotations

import asyncio
import os
import re
import shutil
from collections import deque
from pathlib import Path

import yaml

from . import jar_cache
from .config import SERVERS_ROOT
from .models import Server
from .versions import download_file, get_server_download

# 状态常量
STATUS_INSTALLING = "installing"
STATUS_ERROR = "error"
STATUS_NEW_SETUP = "new_setup"
STATUS_RUNNING = "running"
STATUS_STOPPED = "stopped"

_INSTALLING_MARKER = ".installing"
_FAILED_MARKER = ".install_failed"

# 控制台:每个实例在内存里保留的最近日志行数,以及订阅队列的上限。
_CONSOLE_BUFFER_LINES = 500
_SUBSCRIBER_QUEUE_MAXSIZE = 1000


def sanitize_dir_name(name: str) -> str:
    """把服务器名净化成安全的目录名。"""
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", name.strip())
    cleaned = cleaned.strip("._") or "server"
    return cleaned[:80]


def _eula_text() -> str:
    return (
        "# Generated by mc-panel. By setting eula=true you agree to the "
        "Minecraft EULA (https://aka.ms/MinecraftEULA).\n"
        "eula=true\n"
    )


def _server_properties_text(port: int) -> str:
    return "\n".join(
        [
            "#Minecraft server properties (generated by mc-panel)",
            f"server-port={port}",
            "online-mode=true",
            "max-players=20",
            "view-distance=10",
            "motd=A Minecraft Server managed by mc-panel",
            "enable-rcon=false",
            "",
        ]
    )


def _mcdr_config(java_command: str, min_memory: str, max_memory: str) -> dict:
    """构造 vanilla 服务器的 MCDR config.yml 内容。"""
    return {
        "language": "zh_cn",
        "working_directory": "server",
        "start_command": [
            java_command,
            f"-Xms{min_memory}",
            f"-Xmx{max_memory}",
            # 强制服务端以 UTF-8 输出,避免 Windows 下控制台用系统码页(GBK)导致乱码
            "-Dfile.encoding=UTF-8",
            "-jar",
            "server.jar",
            "nogui",
        ],
        "handler": "vanilla_handler",
        # 发送给服务端用 UTF-8;读取服务端输出先按 UTF-8,失败回退 GBK
        # (Windows 下 Java 启动器/旧服务端常用系统码页),避免解码报错。
        "encoding": "utf8",
        "decoding": ["utf8", "gbk"],
        "plugin_directories": ["plugins"],
        "check_update": False,
        "advanced_console": False,
        "telemetry": False,
    }


def _permission_text() -> str:
    return "\n".join(
        ["default_level: user", "owner:", "admin:", "helper:", "user:", "guest:", ""]
    )


class MCDRManager:
    def __init__(self) -> None:
        # server_id -> asyncio subprocess
        self._procs: dict[int, asyncio.subprocess.Process] = {}
        # server_id -> 最近日志行的环形缓冲(供控制台连接时回放历史)
        self._buffers: dict[int, deque[str]] = {}
        # server_id -> 订阅该实例输出的队列集合(每个 WebSocket 连接一个)
        self._subscribers: dict[int, set[asyncio.Queue[str]]] = {}
        # server_id -> 读取 stdout 的后台任务
        self._reader_tasks: dict[int, asyncio.Task] = {}
        # server_id -> (已下载字节, 总字节);安装/下载进度
        self._install_progress: dict[int, tuple[int, int]] = {}
        # server_id -> 安装(下载)任务,用于中止
        self._install_tasks: dict[int, asyncio.Task] = {}

    # ---------- 路径 ----------
    def instance_dir(self, server: Server) -> Path:
        return SERVERS_ROOT / server.dir_name

    def clear_stale_installing(self) -> None:
        """启动时调用:残留的 .installing 标记都已失效(下载随进程退出无法续传),
        统一转成失败标记,让实例显示为「异常」并可重新安装,而不是永远「安装中」。"""
        if not SERVERS_ROOT.exists():
            return
        for inst in SERVERS_ROOT.iterdir():
            marker = inst / _INSTALLING_MARKER
            if marker.exists():
                marker.unlink(missing_ok=True)
                (inst / _FAILED_MARKER).write_text(
                    "安装被中断(服务重启),请点「重新安装」重试", encoding="utf-8"
                )

    # ---------- 状态 ----------
    def get_status(self, server: Server) -> str:
        inst = self.instance_dir(server)
        if (inst / _INSTALLING_MARKER).exists():
            return STATUS_INSTALLING
        if (inst / _FAILED_MARKER).exists():
            return STATUS_ERROR
        if not (inst / "server" / "server.jar").exists():
            return STATUS_NEW_SETUP
        proc = self._procs.get(server.id)
        if proc is not None and proc.returncode is None:
            return STATUS_RUNNING
        return STATUS_STOPPED

    # ---------- 安装进度 / 任务 ----------
    def install_progress(self, server_id: int) -> tuple[int, int] | None:
        return self._install_progress.get(server_id)

    def set_install_task(self, server_id: int, task: asyncio.Task) -> None:
        self._install_tasks[server_id] = task

    def clear_install_task(self, server_id: int) -> None:
        self._install_tasks.pop(server_id, None)
        self._install_progress.pop(server_id, None)

    async def cancel_install(self, server: Server) -> None:
        """中止进行中的安装:取消下载任务并把实例标记为失败(可重试)。"""
        task = self._install_tasks.get(server.id)
        if task is not None and not task.done():
            task.cancel()
        inst = self.instance_dir(server)
        (inst / _INSTALLING_MARKER).unlink(missing_ok=True)
        (inst / _FAILED_MARKER).write_text("已取消安装,可点「重试」重新下载", encoding="utf-8")
        self._install_progress.pop(server.id, None)
        self._install_tasks.pop(server.id, None)

    async def _fetch_jar(self, server: Server, dest: Path) -> None:
        """获取服务端 jar:命中本地缓存则复用,否则下载、校验 sha1 并入缓存。
        进度总量用 meta 的 size。"""
        info = await get_server_download(server.mc_version)
        sha1 = info.get("sha1", "")
        size = info.get("size", 0) or 0
        self._install_progress[server.id] = (0, size)

        cached = jar_cache.lookup(sha1)
        if cached is not None and (size == 0 or cached.stat().st_size == size):
            shutil.copyfile(cached, dest)
            self._install_progress[server.id] = (size, size)
            return

        await download_file(
            info["url"],
            dest,
            progress=lambda d, t: self._install_progress.__setitem__(server.id, (d, size or t)),
        )
        if sha1 and jar_cache.compute_sha1(dest) != sha1:
            raise RuntimeError("下载校验失败:sha1 不匹配")
        jar_cache.store(sha1, dest, server.mc_version, size or dest.stat().st_size)

    # ---------- 创建 ----------
    async def create_instance(self, server: Server, java_command: str) -> None:
        """生成实例目录并下载服务端 jar。耗时较长,应在后台任务中调用。"""
        inst = self.instance_dir(server)
        server_dir = inst / "server"
        marker = inst / _INSTALLING_MARKER
        failed = inst / _FAILED_MARKER

        try:
            for sub in (server_dir, inst / "plugins", inst / "config", inst / "logs"):
                sub.mkdir(parents=True, exist_ok=True)
            if failed.exists():
                failed.unlink()
            marker.write_text("installing", encoding="utf-8")
            self._install_progress[server.id] = (0, 0)

            (inst / "config.yml").write_text(
                yaml.safe_dump(
                    _mcdr_config(java_command, server.min_memory, server.max_memory),
                    allow_unicode=True,
                    sort_keys=False,
                ),
                encoding="utf-8",
            )
            (inst / "permission.yml").write_text(_permission_text(), encoding="utf-8")
            (server_dir / "eula.txt").write_text(_eula_text(), encoding="utf-8")
            (server_dir / "server.properties").write_text(
                _server_properties_text(server.port), encoding="utf-8"
            )

            await self._fetch_jar(server, server_dir / "server.jar")

            marker.unlink(missing_ok=True)
            self._install_progress.pop(server.id, None)
        except Exception as exc:  # noqa: BLE001 - 记录失败原因供前端显示
            marker.unlink(missing_ok=True)
            failed.write_text(str(exc), encoding="utf-8")
            self._install_progress.pop(server.id, None)
            raise

    # ---------- 控制台:缓冲与订阅 ----------
    def _append_line(self, server_id: int, line: str) -> None:
        buf = self._buffers.setdefault(server_id, deque(maxlen=_CONSOLE_BUFFER_LINES))
        buf.append(line)
        for queue in list(self._subscribers.get(server_id, set())):
            try:
                queue.put_nowait(line)
            except asyncio.QueueFull:
                pass  # 慢消费者:丢弃该行而非阻塞读取

    def recent_lines(self, server_id: int) -> list[str]:
        return list(self._buffers.get(server_id, ()))

    def subscribe(self, server_id: int) -> asyncio.Queue[str]:
        queue: asyncio.Queue[str] = asyncio.Queue(maxsize=_SUBSCRIBER_QUEUE_MAXSIZE)
        self._subscribers.setdefault(server_id, set()).add(queue)
        return queue

    def unsubscribe(self, server_id: int, queue: asyncio.Queue[str]) -> None:
        subs = self._subscribers.get(server_id)
        if subs:
            subs.discard(queue)

    async def _read_output(self, server_id: int, proc: asyncio.subprocess.Process) -> None:
        """持续读取子进程输出,逐行写入缓冲并广播给订阅者。"""
        assert proc.stdout is not None
        while True:
            raw = await proc.stdout.readline()
            if not raw:
                break
            self._append_line(server_id, raw.decode("utf-8", errors="replace").rstrip("\r\n"))
        rc = proc.returncode
        self._append_line(server_id, f"[mc-panel] 进程已退出 (return code: {rc})")

    def _reconcile_config(self, inst: Path) -> None:
        """启动前同步实例 config.yml 的编码字段,让早于编码修复创建的实例也受益。
        只改 encoding/decoding,不动用户可能自定义的 start_command。"""
        config_path = inst / "config.yml"
        if not config_path.exists():
            return
        try:
            data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001 - 配置损坏时不阻塞启动
            return
        if data.get("encoding") == "utf8" and data.get("decoding") == ["utf8", "gbk"]:
            return
        data["encoding"] = "utf8"
        data["decoding"] = ["utf8", "gbk"]
        config_path.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8"
        )

    def _apply_java(self, inst: Path, java_path: str) -> None:
        """把所选 java 写入实例 config.yml 的 start_command[0](保留其余参数)。"""
        config_path = inst / "config.yml"
        if not config_path.exists():
            return
        try:
            data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001
            return
        cmd = data.get("start_command")
        if isinstance(cmd, list) and cmd and cmd[0] != java_path:
            cmd[0] = java_path
            data["start_command"] = cmd
            config_path.write_text(
                yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8"
            )

    # ---------- 编辑:把改动落到实例文件 ----------
    def apply_memory(self, server: Server) -> None:
        """把 server 的 min/max 内存写入 config.yml 的 start_command(-Xms/-Xmx)。"""
        config_path = self.instance_dir(server) / "config.yml"
        if not config_path.exists():
            return
        try:
            data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except Exception:  # noqa: BLE001
            return
        cmd = data.get("start_command")
        if not isinstance(cmd, list) or not cmd:
            return
        new_cmd: list = []
        had_xms = had_xmx = False
        for tok in cmd:
            if isinstance(tok, str) and tok.startswith("-Xms"):
                new_cmd.append(f"-Xms{server.min_memory}")
                had_xms = True
            elif isinstance(tok, str) and tok.startswith("-Xmx"):
                new_cmd.append(f"-Xmx{server.max_memory}")
                had_xmx = True
            else:
                new_cmd.append(tok)
        # 缺失则补在 java 可执行文件(index 0)之后
        if not had_xmx:
            new_cmd.insert(1, f"-Xmx{server.max_memory}")
        if not had_xms:
            new_cmd.insert(1, f"-Xms{server.min_memory}")
        data["start_command"] = new_cmd
        config_path.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False), encoding="utf-8"
        )

    def apply_port(self, server: Server) -> None:
        """把 server.port 写入 server/server.properties 的 server-port。"""
        props = self.instance_dir(server) / "server" / "server.properties"
        if not props.exists():
            return
        out: list[str] = []
        found = False
        for line in props.read_text(encoding="utf-8").splitlines():
            if line.startswith("server-port="):
                out.append(f"server-port={server.port}")
                found = True
            else:
                out.append(line)
        if not found:
            out.append(f"server-port={server.port}")
        props.write_text("\n".join(out) + "\n", encoding="utf-8")

    async def redownload_jar(self, server: Server) -> None:
        """更换版本:仅重新下载 server.jar(保留世界/配置)。"""
        inst = self.instance_dir(server)
        server_dir = inst / "server"
        server_dir.mkdir(parents=True, exist_ok=True)
        marker = inst / _INSTALLING_MARKER
        failed = inst / _FAILED_MARKER
        try:
            failed.unlink(missing_ok=True)
            marker.write_text("installing", encoding="utf-8")
            self._install_progress[server.id] = (0, 0)
            await self._fetch_jar(server, server_dir / "server.jar")
            marker.unlink(missing_ok=True)
            self._install_progress.pop(server.id, None)
        except Exception as exc:  # noqa: BLE001
            marker.unlink(missing_ok=True)
            failed.write_text(str(exc), encoding="utf-8")
            self._install_progress.pop(server.id, None)
            raise

    # ---------- 启停 ----------
    async def start(
        self, server: Server, python_executable: str, java_path: str | None = None
    ) -> None:
        inst = self.instance_dir(server)
        if not (inst / "server" / "server.jar").exists():
            raise RuntimeError("服务端 jar 不存在,实例尚未安装完成")
        self._reconcile_config(inst)
        if java_path:
            self._apply_java(inst, java_path)
        existing = self._procs.get(server.id)
        if existing is not None and existing.returncode is None:
            return  # 已在运行

        # 强制 MCDR(Python)以 UTF-8 读写其 stdio,否则 Windows 下会用系统码页(GBK)
        # 写日志,我们按 UTF-8 解码就会乱码。这样无论宿主机区域设置如何都统一为 UTF-8。
        env = {**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"}
        proc = await asyncio.create_subprocess_exec(
            python_executable,
            "-m",
            "mcdreforged",
            cwd=str(inst),
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            env=env,
        )
        self._procs[server.id] = proc
        # 新一轮运行清空旧缓冲,并启动输出读取任务
        self._buffers[server.id] = deque(maxlen=_CONSOLE_BUFFER_LINES)
        self._append_line(server.id, "[mc-panel] 实例已启动")
        self._reader_tasks[server.id] = asyncio.create_task(self._read_output(server.id, proc))

    async def send_command(self, server: Server, command: str) -> None:
        proc = self._procs.get(server.id)
        if proc is None or proc.returncode is not None or proc.stdin is None:
            raise RuntimeError("实例未在运行")
        try:
            proc.stdin.write((command.rstrip("\n") + "\n").encode("utf-8"))
            await proc.stdin.drain()
        except (BrokenPipeError, ConnectionResetError) as exc:
            raise RuntimeError("无法写入实例标准输入") from exc

    async def stop(self, server: Server) -> None:
        proc = self._procs.get(server.id)
        if proc is None or proc.returncode is not None:
            self._procs.pop(server.id, None)
            return
        if proc.stdin is not None:
            try:
                proc.stdin.write(b"stop\n")
                await proc.stdin.drain()
            except (BrokenPipeError, ConnectionResetError):
                proc.terminate()

    async def delete_instance(self, server: Server) -> None:
        await self.stop(server)
        self._procs.pop(server.id, None)
        inst = self.instance_dir(server)
        if inst.exists():
            shutil.rmtree(inst, ignore_errors=True)


# 单例
manager = MCDRManager()
