"""Velocity 代理网络:一键接线主服(velocity)与子服(MC),自动配 modern 转发。

- 主服(velocity):生成/复用 forwarding.secret,velocity.toml 设 modern + [servers]。
- 子服:online-mode=false;按加载器装转发 mod 并写密钥:
    fabric → FabricProxy-Lite(config/FabricProxy-Lite.toml)
    forge  → Proxy-Compatible-Forge(config/proxy-compatible-forge.toml)
    原版   → 无 mod 加载器,不支持(需改用 fabric/forge)。
"""
from __future__ import annotations

import re
import secrets
from pathlib import Path

from .mcdr import manager
from .mod_manager import manager as mods
from .models import Server

# 子服类型 -> (转发 mod 的 Modrinth slug, modrinth loader)
_FORWARD_MOD = {
    "fabric": ("fabricproxy-lite", "fabric"),
    "forge": ("proxy-compatible-forge", "forge"),
}


def _key(name: str) -> str:
    k = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_").lower()
    return k or "server"


def _secret_file(proxy_inst: Path) -> Path:
    return proxy_inst / "server" / "forwarding.secret"


def read_secret(proxy_inst: Path) -> str:
    """读取 velocity 的 forwarding.secret(不存在返回空串)。"""
    f = _secret_file(proxy_inst)
    if f.exists():
        return f.read_text(encoding="utf-8").strip()
    return ""


def _velocity_secret(proxy_inst: Path, override: str = "") -> str:
    f = _secret_file(proxy_inst)
    if override:
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(override, encoding="utf-8")
        return override
    cur = read_secret(proxy_inst)
    if cur:
        return cur
    s = secrets.token_hex(16)
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(s, encoding="utf-8")
    return s


def _write_velocity_toml(proxy: Server, backends: list[Server]) -> None:
    """重写 velocity.toml:modern 转发 + 各子服。"""
    inst = manager.instance_dir(proxy) / "server"
    inst.mkdir(parents=True, exist_ok=True)
    servers_lines = [f'{_key(b.name)} = "127.0.0.1:{b.port}"' for b in backends]
    first = _key(backends[0].name) if backends else "lobby"
    toml = f"""# Generated by mc-panel (代理网络一键接线)
config-version = "2.7"
bind = "0.0.0.0:{proxy.port}"
motd = "<#09add3>A Velocity Server"
show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"

[servers]
{chr(10).join(servers_lines)}
try = [
    "{first}"
]

[forced-hosts]

[advanced]
[query]
enabled = false
port = {proxy.port}
"""
    (inst / "velocity.toml").write_text(toml, encoding="utf-8")


def _write_fabric_proxy(inst: Path, secret: str) -> None:
    cfg = inst / "server" / "config" / "FabricProxy-Lite.toml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text(
        "hackOnlineMode = true\n"
        "hackMessageChain = true\n"
        "hackEarlySend = false\n"
        'disconnectMessage = "This server requires you to connect with Velocity."\n'
        f'secret = "{secret}"\n',
        encoding="utf-8",
    )


def _write_forge_proxy(inst: Path, secret: str) -> None:
    cfg = inst / "server" / "config" / "proxy-compatible-forge.toml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text(
        "[forwarding]\n"
        "enabled = true\n"
        'mode = "MODERN"\n'
        f'secret = "{secret}"\n',
        encoding="utf-8",
    )


async def _install_forward_mod(server: Server, slug: str, loader: str) -> bool:
    inst = manager.instance_dir(server)
    versions = await mods.list_versions(slug, server.mc_version, loader)
    if not versions:
        return False
    await mods.install_from_modrinth(inst, versions[0]["id"], mc_version=server.mc_version)
    return True


async def wire(proxy: Server, backends: list[Server], secret_override: str = "") -> list[dict]:
    """执行接线,返回每个子服的结果 [{name, status, detail}]。"""
    secret = _velocity_secret(manager.instance_dir(proxy), secret_override.strip())
    _write_velocity_toml(proxy, backends)

    results: list[dict] = []
    for b in backends:
        inst = manager.instance_dir(b)
        # 子服必须关闭正版验证(由代理鉴权)
        manager.write_properties(b, {"online-mode": "false"})
        mod = _FORWARD_MOD.get(b.server_type)
        if not mod:
            results.append({"name": b.name, "status": "unsupported", "detail": "原版无 mod 加载器,无法做 modern 转发(请改用 Fabric/Forge)"})
            continue
        slug, loader = mod
        try:
            ok = await _install_forward_mod(b, slug, loader)
            if not ok:
                results.append({"name": b.name, "status": "error", "detail": f"未找到适配 {b.mc_version} 的 {slug}"})
                continue
            if b.server_type == "fabric":
                _write_fabric_proxy(inst, secret)
            else:
                _write_forge_proxy(inst, secret)
            results.append({"name": b.name, "status": "ok", "detail": f"已装 {slug} 并写入密钥"})
        except Exception as exc:  # noqa: BLE001
            results.append({"name": b.name, "status": "error", "detail": str(exc)})
    return results
